---
- name: Start redis docker containers
  become: yes
  docker_container:
    name: redis
    image: redis:6.2.1
    state: started
    ports:
      - 6379:6379
    restart_policy: unless-stopped
    volumes:
      - /srv/newsblur/docker/volumes/redis:/data
      - /srv/newsblur/config/redis.conf:/usr/local/etc/redis_server.conf
      - /srv/newsblur/config/redis_docker.conf:/etc/redis_server.conf
      - /srv/newsblur/docker/volumes/redis.var.lib:/var/lib/redis

- name: Register redis in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/redis.json
  notify:
    - reload consul

- name: Link disk usage sanity checker
  become: yes
  file:
   src: "/srv/newsblur/utils/monitor_disk_usage.py"
   dest: "/etc/cron.daily/monitor_disk_usage"
   state: link

- name: Make docker network for newsblurnet
  become: yes
  docker_network:
    name: newsblurnet
  notify: restart docker

- name: Create docker container for Redis bgsave sanity checkers
  become: yes
  docker_container:
    name: "sanity_checkers"
    image: newsblur/newsblur_python3
    state: started
    pull: yes
    container_default_behavior: no_defaults
    restart_policy: always
    command: /bin/bash -c "while true; do sleep 15 ; done"
    networks_cli_compatible: yes
    network_mode: default
    networks:
      - name: newsblurnet
    volumes:
      - /srv/newsblur/utils/monitor_redis_bgsave.py:/etc/cron.daily/monitor_redis_bgsave.py
