---
- name: Start redis docker containers
  become: yes
  docker_container:
    name: redis
    image: redis:6.2.1
    state: started
    ports:
      - 6379:6379
    restart_policy: unless-stopped
    volumes:
      - /srv/newsblur/docker/volumes/redis:/data
      - /srv/newsblur/config/redis.conf:/usr/local/etc/redis_server.conf
      - /srv/newsblur/config/redis_docker.conf:/etc/redis_server.conf
      - /srv/newsblur/docker/volumes/redis.var.lib:/var/lib/redis

- name: Register redis in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/redis.json
  notify:
    - reload consul

- name: Add sanity checkers cronjob for disk usage
  become: yes
  cron:
    name: disk_usage_sanity_checker
    special_time: daily
    job: docker pull newsblur/newsblur_python3:latest;
      docker run --rm
      output=$(eval sudo df / | head -n 2 |  tail -1);
      -v /srv/newsblur:/srv/newsblur
      --network=newsblurnet --hostname {{ ansible_hostname }} 
      newsblur/newsblur_python3 /srv/newsblur/utils/monitor_disk_usage.py $output

- name: Make docker network for newsblurnet
  become: yes
  docker_network:
    name: newsblurnet
  notify: restart docker

- name: Get log file location for redis
  become: yes
  shell: docker inspect --format="{{ '{{' }}.LogPath {{ '}}' }}" redis
  register: redis_log_path

- name: show redis_log_path
  debug:
    msg: "{{ redis_log_path.stdout }}"

- name: Add sanity checkers cronjob for redis bg_save
  become: yes
  cron:
    name: redis_bg_save_sanity_checker
    special_time: daily
    job: docker pull newsblur/newsblur_python3:latest;
      docker run --rm -v {{redis_log_path.stdout}}:{{redis_log_path.stdout}} -v /srv/newsblur:/srv/newsblur --network=newsblurnet newsblur/newsblur_python3 /srv/newsblur/utils/monitor_redis_bgsave.py {{redis_log_path.stdout}}
  when: "'redis' in inventory_hostname"
  tags:
    - sanity-checker

- name: Add redis backup
  cron:
    name: "{{ ansible_hostname }} backup"
    minute: "0"
    hour: "4"
    job: "/srv/newsblur/utils/backups/backup_redis.py {{ ansible_hostname}}"