---
- name: Start redis docker containers
  become: yes
  docker_container:
    name: redis
    image: redis:6.2.1
    state: started
    ports:
      - 6379:6379
    restart_policy: unless-stopped
    volumes:
      - /srv/newsblur/docker/volumes/redis:/data
      - /srv/newsblur/config/redis.conf:/usr/local/etc/redis_server.conf
      - /srv/newsblur/config/redis_docker.conf:/etc/redis_server.conf
      - /srv/newsblur/docker/volumes/redis.var.lib:/var/lib/redis

- name: Register redis in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/redis.json
  notify:
    - reload consul

- name: Link disk usage sanity checker
  become: yes
  file:
   src: "/srv/newsblur/utils/monitor_disk_usage.py"
   dest: "/etc/cron.daily/monitor_disk_usage"
   state: link

- name: Add sanity checkers cronjob for disk usage
  become: yes
  cron:
    name: disk_usage_sanity_checker
    special_time: daily
    job: docker pull newsblur/newsblur_python3:latest;
      docker run --rm
      -v /srv/newsblur:/srv/newsblur
      --network=newsblurnet /srv/newsblur/utils/monitor_disk_usage.py
  tags:
    - sanity-checker

- name: Make docker network for newsblurnet
  become: yes
  docker_network:
    name: newsblurnet
  notify: restart docker

- name: Add sanity checkers cronjob for redis bg_save
  become: yes
  cron:
    name: redis_bg_save_sanity_checker
    special_time: daily
    job: docker pull newsblur/newsblur_python3:latest;
      docker run --rm
      -v /srv/newsblur:/srv/newsblur
      --network=newsblurnet /srv/newsblur/utils/monitor_redis_bgsave.py
  when: "'redis' in inventory_hostname"
  tags:
    - sanity-checker