---
- name: reload sentry
  become: yes
  block:
    - name: Updating Sentry
      command:
        chdir: /srv/sentry/
        cmd: ./install.sh
    - name: docker-compuse up -d
      command:
        chdir: /srv/sentry/
        cmd: docker-compose up -d
  listen: reload sentry
