---

- name: Ensure directories required
  become: yes
  file:
    dest: '{{ item }}'
    state: directory
  with_items:
    - /etc/netdata
    - /etc/netdata/conf.d
    - /etc/netdata/charts.d
    - /etc/netdata/node.d
    - /etc/netdata/plugins.d
    - /etc/netdata/python.d

- name: Set system hostname as netdata hostname
  become: yes
  copy:
    dest: /etc/netdata/conf.d/netdata.conf
    content: |
      [global]
        hostname = {{ hostname }}
  register: netdata_conf

- name: Set environment variables
  become: yes
  template:
    dest: /etc/netdata/environment
    src: environment.j2
    mode: 0600
  register: configuration

- name: Setup Netdata docker container
  become: yes
  docker_container:
    name: netdata
    state: started
    image: netdata/netdata
    ports: 19999:19999
    hostname: "{{ ansible_hostname }}"
    volumes:
    - /srv/newsblur/docker/netdata/netdatalib:/var/lib/netdata
    - /srv/newsblur/docker/netdata/netdatacache:/var/cache/netdata
    - /srv/newsblur/docker/netdata/netdata.conf:/etc/netdata/netdata.conf
    - /srv/newsblur/docker/netdata/netdataconfig/python.d/newsblur_data_request.py:/usr/libexec/netdata/python.d/newsblur_data_request.chart.py
    - /srv/newsblur/docker/netdata/netdataconfig/python.d.conf:/usr/lib/netdata/conf.d/python.d.conf 
    - /srv/newsblur/docker/netdata/netdataconfig/python.d/newsblur_data_request.conf:/usr/lib/netdata/conf.d/python.d/newsblur_data_request.conf
    - /srv/newsblur/utils/netdata/config/go.d.conf:/usr/lib/netdata/conf.d/go.d.conf

    - /etc/passwd:/host/etc/passwd:ro
    - /etc/group:/host/etc/group:ro
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /etc/os-release:/host/etc/os-release:ro
    restart: yes
  
- name: Wait for netdata to start
  wait_for: port=19999 delay=10

- name: Add netdata agent to war room
  become: yes
  ignore_errors: yes
  command: docker exec netdata netdata-claim.sh -token={{ netdata_token }} -rooms={{ netdata_room }} -url={{ netdata_url }} -hostname={{ ansible_hostname }}