---
- name: Copy common secrets
  copy:
    src: /srv/secrets-newsblur/settings/common_settings.py
    dest: /srv/newsblur/newsblur_web/local_settings.py
  register: app_changed

- name: Copy app env
  copy:
    src: /srv/secrets-newsblur/settings/app_env.py
    dest: /srv/newsblur/newsblur_web/app_env.py
  register: app_changed

- name: Add SERVER_NAME to app env
  lineinfile:
    path: /srv/newsblur/newsblur_web/app_env.py
    line: 'SERVER_NAME = "{{ inventory_hostname }}"'

- name: Register flask_metrics in consul
  tags: consul
  become: yes
  template:
    src: /srv/newsblur/ansible/roles/flask_metrics/templates/consul_service.json
    dest: /etc/consul.d/flask_metrics.json
  notify:
    - reload consul
  when: disable_consul_services_ie_staging is not defined

- name: Make docker network for newsblurnet
  become: yes
  docker_network:
    name: newsblurnet
  notify: restart docker

- name: Start flask_metrics docker container
  become: yes
  docker_container:
    name: flask_metrics
    image: newsblur/flask_metrics:latest
    pull: yes
    state: started
    command: bash -c "python /srv/newsblur/flask_metrics/flask_metrics.py"
    hostname: "{{ inventory_hostname }}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    volumes:
      - /srv/newsblur:/srv/newsblur
    networks_cli_compatible: yes
    network_mode: default
    networks:
      - name: newsblurnet
    ports:
      - "5000:5000"

- name: Restart monitor
  become: yes
  shell:
    cmd: docker restart monitor
