---
- name: Start node-exporter container
  become: yes
  docker_container:
    name: node-exporter
    image: prom/node-exporter
    ports:
    - '9100:9100'

- name: Register node-exporter in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/node-exporter.json
  notify:
    - reload consul
  with_items:
    - service_name: node-exporter