---
- name: Start node docker containers
  become: yes
  docker_container:
    name: node
    image: newsblur/newsblur_node
    state: started
    command: node /srv/node/newsblur.js
    container_default_behavior: no_defaults
    pull: true
    network_mode: host
    env:
      NODE_ENV: "production"
    restart_policy: unless-stopped
    volumes:
      - /srv/newsblur/node:/srv/node
  with_items:
    - node-socket
    - node-page
    - node-text
    - node-favicons
    - staging
  when: item in inventory_hostname

- name: Start non-newsblur node docker containers
  become: yes
  docker_container:
    name: "{{ item.container_name }}"
    image: "{{ item.image }}"
    state: started
    container_default_behavior: no_defaults
    pull: true
    ports: 
      - "{{ item.ports }}"
    env:
      NODE_ENV: "production"
    restart_policy: unless-stopped
    volumes:
      - /srv/newsblur/node:/srv/node
  with_items:
    - container_name: imageproxy
      image: willnorris/imageproxy
      ports: 8088:8080
      target_host: node-images
  when: item.target_host in inventory_hostname

- name: Register nodes in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/{{item.target_host}}.json
  with_items:
    - target_host: node-socket
      port: 8008
    - target_host: node-page
      port: 8008
    - target_host: node-text
      port: 8008
    - target_host: node-favicons
      port: 8008
    - target_host: node-images
      port: 8088
  notify:
    - reload consul
  when: item.target_host in inventory_hostname and disable_consul_services is not defined
