---
- name: Template file for prometheus
  template:
    src: /srv/newsblur/docker/prometheus/prometheus.consul.yml.j2
    dest: /srv/newsblur/docker/prometheus/prometheus.yml

- name: Register prometheus in consul
  tags: consul
  become: yes
  template:
    src: /srv/newsblur/ansible/roles/prometheus/templates/consul_service.json
    dest: /etc/consul.d/prometheus.json
  notify:
    - reload consul

- name: Start prometheus docker container
  become: yes
  docker_container:
    name: prometheus
    image: prom/prometheus
    user: root
    state: started
    restart_policy: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /srv/newsblur/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /srv/newsblur/docker/volumes/prometheus_data:/prometheus
