---
- hosts: app
  gather_facts: false
  # serial: "50%"
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml

  tasks:
    # - name: Leave consul
    #   command: consul leave
    #   ignore_errors: yes

    - name: Pull newsblur_web github
      git:
        repo: https://github.com/samuelclay/NewsBlur.git
        dest: /srv/newsblur/
        version: dashboard3
      register: pulled
    
    - name: Reload gunicorn
      become: yes
      block:
        - name: Find gunicorn master process
          shell: "ps -C gunicorn fch -o pid | head -n 1"
          register: psaux
        - name: Reload gunicorn
          command: "kill -HUP {{ psaux.stdout }}"
      # when: pulled.changed

    - name: Start Consul
      become: yes
      service:
        name: consul
        state: started
        enabled: true
